Jwt:
  method: "HS256" # 签名算法：持对称算法（HS256/HS384/HS512）和非对称算法（RS256/RS384/RS512/ES256/ES384/ES512/Ed25519）
  key: "Su-chat-secret-key"  # 签名/验签密钥：HS 系列对称算法需传入字符串密钥（建议 ≥32 字节，高复杂度）；RS 系列非对称算法需传入公钥/私钥路径
  expiry: 7200 # Token 过期时间（单位：秒），默认 7200 秒（2 小时）
  refresh_expiry: 86400 # 刷新 Token 过期时间（单位：秒），默认 86400 秒（24 小时）


